language: generic
sudo: required

services:
  - docker

before install:
  - docker build -t minniaturepug/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true miniaturepug/react-test npm test

after_success:
  - docker build -t miniaturepug/complex-client ./client
  - docker build -t miniaturepug/complex-nginx ./nginx
  - docker build -t miniaturepug/complex-server ./server
  - docker build -t miniaturepug/complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push miniaturepug/complex-client
  - docker push miniaturepug/complex-nginx
  - docker push miniaturepug/complex-server
  - docker push miniaturepug/complex-worker
